# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# development:
#   <<: *default
#   database: challenge_development

# test:
#   <<: *default
#   database: challenge_test

# production:
#   <<: *default
#   url: <%= ENV["DATABASE_URL"] %>



# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   host: 127.0.0.1
#   port: 5433  
#   username: postgres
#   password: pradh

# development:
#   <<: *default
#   database: challenge_development

# test:
#   <<: *default
#   database: challenge_test

# production:
#   <<: *default
#   url: <%= ENV["DATABASE_URL"] %>


default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: challenge_development

test:
  <<: *default
  database: challenge_test

production:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
